import { Category } from './types';

export const EVIDENCE_TYPES = [
  'Email',
  'Text Message',
  'Voicemail',
  'Billing Record',
  'Court Order',
  'Transcript',
  'Witness Statement',
  'Social Media',
  'Financial Document',
  'Other'
];

export const GLOSSARY_TERMS = [
  { term: 'Affidavit', definition: 'A written statement confirmed by oath or affirmation, for use as evidence in court.' },
  { term: 'Attorney-Client Privilege', definition: 'A legal privilege that keeps communications between an attorney and their client confidential.' },
  { term: 'Conflict of Interest', definition: 'A situation in which a person or firm has a duty to more than one person or organization, but cannot satisfy both because the interests are adverse.' },
  { term: 'Deposition', definition: 'The process of giving sworn evidence. A witness is questioned by attorneys before a trial, and a transcript is made.' },
  { term: 'Discovery', definition: 'The formal process of exchanging information between the parties about the witnesses and evidence they will present at trial.' },
  { term: 'Ex Parte', definition: 'A communication with the judge by one party without the other party present. Generally prohibited unless specifically allowed by law (e.g., in emergencies).' },
  { term: 'Fiduciary Duty', definition: 'A legal obligation of one party to act in the best interest of another. Attorneys have a fiduciary duty to their clients.' },
  { term: 'GAL (Guardian ad Litem)', definition: 'An attorney or mental health professional appointed by the court to represent the best interests of the child in a custody dispute.' },
  { term: 'Interrogatories', definition: 'Written questions sent by one party to another, which must be answered in writing under oath.' },
  { term: 'Motion', definition: 'A formal request made to a judge for an order or judgment.' },
  { term: 'Perjury', definition: 'The offense of willfully telling an untruth in a court after having taken an oath or affirmation.' },
  { term: 'Pleading', definition: 'A formal written statement of a party’s claims or defenses to another party’s claims in a civil action.' },
  { term: 'Pro Se', definition: 'Representing oneself in court without an attorney.' },
  { term: 'Retainer', definition: 'A fee paid in advance to an attorney to secure their services.' },
  { term: 'Sanctions', definition: 'Penalties imposed by the court for violating rules, court orders, or filing frivolous motions.' },
  { term: 'Subpoena', definition: 'A writ ordering a person to attend a court or to produce documents.' },
  { term: 'Work Product', definition: 'Material prepared by an attorney in anticipation of litigation, which is generally protected from discovery.' },
];

export const CATEGORIES: Category[] = [
  {
    id: 'I',
    title: 'Dishonesty, Misrepresentation & Fraud',
    range: '1–15',
    items: [
      { id: '1', text: 'Knowingly lying to the court.' },
      { id: '2', text: 'Misrepresenting facts in pleadings.' },
      { id: '3', text: 'Fabricating evidence or encouraging a client to do so.' },
      { id: '4', text: 'Misquoting case law or statutes.' },
      { id: '5', text: 'Altering or withholding documents.' },
      { id: '6', text: 'Coaching a client to give misleading testimony.' },
      { id: '7', text: 'Filing motions with knowingly false allegations.' },
      { id: '8', text: 'Hiding material facts from the court.' },
      { id: '9', text: 'Falsifying billing records.' },
      { id: '10', text: 'Misrepresenting settlement offers to clients.' },
      { id: '11', text: 'Lying about court dates or scheduling conflicts.' },
      { id: '12', text: 'Using “creative” interpretations of evidence to deceive.' },
      { id: '13', text: 'Making misleading statements about court orders.' },
      { id: '14', text: 'Concealing a client’s criminal history or violations.' },
      { id: '15', text: 'Misleading clients about case outcomes to secure larger retainers.' },
    ],
  },
  {
    id: 'II',
    title: 'Conflicts of Interest',
    range: '16–27',
    items: [
      { id: '16', text: 'Representing conflicting family members without proper waiver.' },
      { id: '17', text: 'Taking cases involving former clients where confidential information may be used unfairly.' },
      { id: '18', text: 'Serving as both mediator and attorney in the same dispute.' },
      { id: '19', text: 'Maintaining personal relationships with judges or GALs not disclosed to clients.' },
      { id: '20', text: 'Accepting gifts from a GAL, psychologist, or evaluator involved in the case.' },
      { id: '21', text: 'Representing both parents in a divorce at different times without proper conflict checks.' },
      { id: '22', text: 'Failing to disclose personal friendships with expert witnesses.' },
      { id: '23', text: 'Referring clients to “preferred providers” in exchange for kickbacks.' },
      { id: '24', text: 'Sharing confidential information with third parties for strategic gain.' },
      { id: '25', text: 'Using opposing party’s former attorney as a consultant without conflict review.' },
      { id: '26', text: 'Recommending expensive services from which the attorney receives a financial benefit.' },
      { id: '27', text: 'Handling real estate or business transactions for the client without competence/consent.' },
    ],
  },
  {
    id: 'III',
    title: 'Billing Abuse & Financial Misconduct',
    range: '28–43',
    items: [
      { id: '28', text: 'Inflating time entries.' },
      { id: '29', text: 'Billing multiple clients for the same hours.' },
      { id: '30', text: 'Charging for unnecessary motions to increase conflict.' },
      { id: '31', text: 'Charging for clerical tasks as attorney-level work.' },
      { id: '32', text: 'Charging for time spent correcting their own mistakes.' },
      { id: '33', text: 'Running up discovery costs with no strategic purpose.' },
      { id: '34', text: 'Failing to refund unearned retainers.' },
      { id: '35', text: 'Keeping dormant retainers without accounting.' },
      { id: '36', text: 'Billing clients for personal or unrelated tasks.' },
      { id: '37', text: 'Charging excessive fees in violation of Rule 1.5.' },
      { id: '38', text: 'Withholding billing records from clients.' },
      { id: '39', text: 'Double-charging for travel time and legal time.' },
      { id: '40', text: 'Submitting vague or ambiguous invoices on purpose.' },
      { id: '41', text: 'Failing to disclose foreseeable total litigation costs.' },
      { id: '42', text: 'Creating unnecessary emergencies to bill more.' },
      { id: '43', text: 'Threatening to withdraw unless the client pays questionable charges.' },
    ],
  },
  {
    id: 'IV',
    title: 'Neglect & Incompetence',
    range: '44–60',
    items: [
      { id: '44', text: 'Missing filing deadlines.' },
      { id: '45', text: 'Failing to appear at hearings.' },
      { id: '46', text: 'Inadequate preparation for trial.' },
      { id: '47', text: 'Ignoring client emails or calls for weeks.' },
      { id: '48', text: 'Not reviewing opposing counsel’s filings.' },
      { id: '49', text: 'Not reading psychological evaluations before trial.' },
      { id: '50', text: 'Failing to subpoena important witnesses.' },
      { id: '51', text: 'Incorrectly calculating child support.' },
      { id: '52', text: 'Improperly drafting parenting plans with dangerous ambiguity.' },
      { id: '53', text: 'Failing to object to harmful or irrelevant evidence.' },
      { id: '54', text: 'Misunderstanding local court rules.' },
      { id: '55', text: 'Not disclosing critical information to clients.' },
      { id: '56', text: 'Allowing a client’s rights to lapse due to inaction.' },
      { id: '57', text: 'Failing to communicate settlement options.' },
      { id: '58', text: 'Giving advice outside their scope of competence (e.g., taxes, psychiatry).' },
      { id: '59', text: 'Not preparing clients for testimony or depositions.' },
      { id: '60', text: 'Failing to protect confidential information.' },
    ],
  },
  {
    id: 'V',
    title: 'Abuse of Process & Frivolous Litigation',
    range: '61–75',
    items: [
      { id: '61', text: 'Filing baseless motions to harass the other parent.' },
      { id: '62', text: 'Weaponizing protective orders for strategic leverage.' },
      { id: '63', text: 'Filing unnecessary discovery requests.' },
      { id: '64', text: 'Using litigation to punish rather than resolve disputes.' },
      { id: '65', text: 'Refiling denied motions without change in circumstances.' },
      { id: '66', text: 'Filing emergency motions without true emergencies.' },
      { id: '67', text: 'Intentionally delaying proceedings to increase fees.' },
      { id: '68', text: 'Creating conflict to extend litigation.' },
      { id: '69', text: 'Threatening opposing counsel without cause.' },
      { id: '70', text: 'Using subpoenas to intimidate witnesses.' },
      { id: '71', text: 'Refusing reasonable settlement offers to prolong the case.' },
      { id: '72', text: 'Filing motions solely to increase the opposing party’s fees.' },
      { id: '73', text: 'Frivolously accusing the other parent of abuse without evidence.' },
      { id: '74', text: 'Filing motions without client consent or knowledge.' },
      { id: '75', text: 'Seeking sanctions on opposing counsel knowing they did nothing wrong.' },
    ],
  },
  {
    id: 'VI',
    title: 'Communication Violations',
    range: '76–85',
    items: [
      { id: '76', text: 'Communicating with represented parties without their attorney present.' },
      { id: '77', text: 'Ignoring client instructions.' },
      { id: '78', text: 'Making major decisions without client approval.' },
      { id: '79', text: 'Failing to warn clients about potential risks.' },
      { id: '80', text: 'Sharing confidential details in public areas (hallways, elevators).' },
      { id: '81', text: 'Disclosing case details to third parties without consent.' },
      { id: '82', text: 'Sending threatening or abusive communications.' },
      { id: '83', text: 'Misleading clients about deadlines or expectations.' },
      { id: '84', text: 'Not providing clients with copies of court filings.' },
      { id: '85', text: 'Failing to obtain informed consent on major case strategy.' },
    ],
  },
  {
    id: 'VII',
    title: 'Courtroom Misconduct',
    range: '86–95',
    items: [
      { id: '86', text: 'Disobeying a judge’s explicit orders.' },
      { id: '87', text: 'Violating rules of candor toward the tribunal.' },
      { id: '88', text: 'Harassing or intimidating witnesses.' },
      { id: '89', text: 'Smuggling inadmissible evidence into testimony.' },
      { id: '90', text: 'Coaching clients to evade questions.' },
      { id: '91', text: 'Making improper objections or trying to mislead the judge.' },
      { id: '92', text: 'Using theatrics meant to manipulate rather than advocate.' },
      { id: '93', text: 'Talking over opposing counsel or the judge.' },
      { id: '94', text: 'Introducing evidence without disclosure.' },
      { id: '95', text: 'Attempting to speak ex parte with the judge.' },
    ],
  },
  {
    id: 'VIII',
    title: 'Professional Conduct & Integrity Issues',
    range: '96–100',
    items: [
      { id: '96', text: 'Practicing law while impaired or intoxicated.' },
      { id: '97', text: 'Failing to supervise paralegals or staff.' },
      { id: '98', text: 'Abandoning clients due to nonpayment without proper notice.' },
      { id: '99', text: 'Retaliating against clients who file complaints.' },
      { id: '100', text: 'Publicly disparaging clients or judges on social media.' },
    ],
  },
];
